language: node_js
node_js:
  - 8
script:
  - eleventy
  - postcss styles.css -o output.css
deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  edge: true
  dir: "dist/"
  prod: true
