language: node_js
node_js:
  - 8
script: del dist && eleventy && postcss src/_assets/stylesheets/app.css -o src/_includes/app.compiled.css && eleventy
deploy:
  provider: netlify
  site: $NETLIFY_SITE
  auth: $NETLIFY_AUTH
  edge: true
  dir: "dist/"
