language: node_js
node_js:
  - 8
jobs:
  include:
    - script: eleventy
    - script: postcss src/_assets/stylesheets/app.css -o src/_includes/app.compiled.css
    - script: eleventy
    - stage: deploy
      script: skip
      deploy:
        provider: netlify
        site: $NETLIFY_SITE
        auth: $NETLIFY_AUTH
        edge: true
        dir: "dist/"
        prod: true

