language: node_js
node_js:
  - 8
script: del dist && eleventy && postcss src/_assets/stylesheets/app.css -o src/_includes/app.compiled.css && eleventy
deploy:
  provider: netlify
  site: <site>
  auth: <encrypted auth>
  edge: true # opt in to dpl v2
  dir: "dist/"
